version: 2

workflows:
  version: 2
  build:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:12
        environment:
          NODE_ENV: test
          PGHOST: localhost
          PGUSER: test_user
          PGDATABASE: split_it_test
      - image: circleci/postgres:11
        environment:
          NODE_ENV: test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: split_it_test
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run: sudo apt install postgresql-client
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package.json" }}
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: npm run dbMigrateTest
      - run: NODE_ENV=test npm run test_mocha
